AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the NewRelic::Observability::Dashboards resource type


#Resources:
#  HelloWorldFunction:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Metadata:
#      BuildMethod: go1.x
#    Properties:
#      Handler: bootstrap
#      Runtime: provided.al2
#      Architectures:
#        - x86_64
#      CodeUri: hello-world/

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      CodeUri: bin/
      Environment:
        Variables:
          LOG_LEVEL: debug

  LiveTest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      CodeUri: bin/
      Environment:
        Variables:
          LOG_LEVEL: debug
          TypeConfigurationFile: TypeConfigurationLive.json

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      CodeUri: bin/
      Environment: 
        Variables: 
          MODE: Test

